### ISSUE TITLE
Need queue funciton

### ISSUE THREAD

**Issue by wcs-bjogus** [westcode-solutions/smsgate#3]
Currently we are limited to the Serial Connection to One Connection at a time. 

If we are going to use snmptt to exec the script on multi hits. 
Or multi traps within 3 secounds they will alla execute the script Before the other has ended.

Not good!

**Comment by wcs-bjogus** [comment]
Options i see:

1. Lock file for the script. 
Good: Simple
Bad: How do we handle the secound sms? Sleep on other process name? 

2. Some simple queue file. (ex snmptt creates/add a csv file with the shell script reads with cronjob)
Good: Rather simple and no extra products/applications are needed.
Bad: SMS will not be sent directly (some delay will be added)

3. Some sort of MessageQueue broaker (AMQ/RabbitMQ)
Good: Should be the most stable and robust solution. 
Bad: Wo go form one simple setup to one more complex. (How do we verify that the MQ broker is alive?!)

I am split should we vote on what option to go with? 
@wcs-clagyl

**Comment by wcs-bjogus** [comment]
Sample of option 2.
https://gist.github.com/erichschroeter/4161264

**Comment by wcs-bjogus** [comment]
@jmolsson feel free to add comments

**Comment by jmolsson** [comment]
I would start with option two, and then add the message queue later if needed. I am a fan of KISS and 'aint gonna need it' :-)

To avoid race conditions I would use a queue directory instead of a queue file, and use one one file per message. If you are using PERL, have a look at IPC::DirQueue.

**Comment by wcs-bjogus** [comment]
Not currently using PERL as we are trying to go KISS. 

Like the Folder idea! 

@wcs-clagyl check with Klas if we can use PERL or if we should stay with only shell script.

**Comment by wcs-bjogus** [comment]
Else I suggest we create one script "Add to Queue" and modify the script we currently have to "Read from Queue".

**Comment by jmolsson** [comment]
> Not currently using PERL as we are trying to go KISS.
> 
> Like the Folder idea!
> 
> @wcs-clagyl check with Klas if we can use PERL or if we should stay with only shell script.

Suggested PERL since snmptt is written in PERL if I'm not mistaken, so it should already be on the system. Also saw that one of your script is using Python, so that could also be an option.

**Comment by wcs-bjogus** [comment]
> Not currently using PERL as we are trying to go KISS.
> Like the Folder idea!
> @wcs-clagyl check with Klas if we can use PERL or if we should stay with only shell script.
> 
> Suggested PERL since snmptt is written in PERL if I'm not mistaken, so it should already be on the system. Also saw that one of your scripts is using Python, so that could also be an option.

Doh!
Correkt when we add the snmptt part we will have to add Perl.

The python script is where we got the insperation to the shell script. 
But I am fine with both Python and Perl. 
I do know how ever that Klas wanted a slim function and as few extra libs/lang as posible. 

Going all in on Perl should work if we are going to use snmptt.

**Comment by wcs-clagyl** [comment]
We should look on https://man.cx/smssend(1) and perhaps get some ideas from there ? 
they use a queue system where each message lands under /var/spool/(SMS?)/{incoming, oubound, sent} or something like that. 
So if a message fails to send, it gets handled , and the "queue" is the incoming folder in itself, and each message becomes a file with a random filename generated. 

Perl will be available on the system yes, which gives us quite a few options on how to handle all of it. Preferably we'd like to tell snmptt to send the message to our "sms-handler" and then the rest of the logic is managed by the "sms-handler".

**Comment by jmolsson** [comment]
Decided to make sure snmptt is single threaded
