### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by jmolsson** [westcode-solutions/smsgate#5]
I think you should disable PUSH to the master branch, and require Pull Requests. I can configure it if you like.

**Comment by wcs-clagyl** [comment]
what's the main difference in workflow when you change to that config ?

**Comment by jmolsson** [comment]
A bit of an overkill for a small project. But the main idea is to make sure that the master branch always is stable. You work in a separate branch and then do a PR to the master branch, and someone has to approve that PR. It can also be integrated with CI and code analysis and stuff, so that your PR is only accepted when all checks have passed.

Example of a pull request for my changes to libbeat is here:
https://github.com/elastic/beats/pull/6878

**Comment by wcs-clagyl** [comment]
Nothing wrong by learning the correct way to setup and do things, even if it's a small project. The sooner we get the rouines and habits down the better.

**Comment by wcs-bjogus** [comment]
> I think you should disable PUSH to the master branch, and require Pull Requests. I can configure it if you like.

Agree we should disable PUSH and require Pull Requests. 
We might have a workflow where we fork projekts to our own accounts and work with them there and then make Pull requests from there to Master. 

Having some CI testing/building on the projects would be lovely.

**Comment by jmolsson** [comment]
For public repos like this we can use TravisCI

**Comment by jmolsson** [comment]
I have mucked about with the settings. You should no longer be able to push directly to master.
