### ISSUE TITLE
Agree on distro to use

### ISSUE THREAD

**Issue by wcs-clagyl** [westcode-solutions/smsgate#6]
So far we've tried 
Alpine 3.x
CentOS 7.x 
Oracle Linux 7.x

Should we aim o pick one of them and focus dev for that , or what's the plan ? personal preference i CenOS 7 , but since 14th of feb 2019 csec announced that Oracle Linux 7.3 is certified and approved. 
https://www.fmv.se/sv/Verksamhet/CSEC---Sveriges-Certifieringsorgan-for-IT-Sakerhet/Certifierade-produkter/Oracle-Linux-73-EAL1/

so far i haven't noticed much differences between centos and oracle, so either one is fine by me.

**Comment by jmolsson** [comment]
How about distributing it like a snap or docker or similar to make it distro independent?

**Comment by wcs-clagyl** [comment]
That would be even better, any limitations with docker when i comes to what hardware ports and such it has access to ?

**Comment by wcs-bjogus** [comment]
+1 for docker but still we then need to agree on an base image.

**Comment by jmolsson** [comment]
If docker then alpine
https://hub.docker.com/_/alpine

**Comment by wcs-bjogus** [comment]
Have not run mutch native docker just OpenSHIFT and then REHL and Cent is the "native". 

Alpine works fine for me

**Comment by wcs-clagyl** [comment]
Alpine it is then. 

Preferably we cater o the free-OS alternatives in order to not lock ourselves into any solutions like OpenSHIFT/RHEL and the like ? 
gives us more leeway to experiment with various solutions and systems underneath the docker solution.
